### PR TITLE
Fix Data Engine Tests - LRQA-67303 LRQA-67495 LRQA-67496 LRQA-67498

### PR DESCRIPTION
**Pull request by thaisfrota**
[LRQA-67303](https://issues.liferay.com/browse/LRQA-67303)
[LRQA-67495](https://issues.liferay.com/browse/LRQA-67495)
[LRQA-67496](https://issues.liferay.com/browse/LRQA-67496)
[LRQA-67498](https://issues.liferay.com/browse/LRQA-67498)

### CODE REVIEW

**Comment by thaisfrota** [comment]
ci:test:sf

**Comment by thaisfrota** [comment]
ci:test:data-engine

**Comment by emanuelfisilva** [comment]
LGTM
Thanks @thaisfrota

**Comment by emanuelfisilva** [comment]
ci:forward

**Pull request closed without merging**
