### PR TITLE
LPS-128369 Add DM smoke test for data engine

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-128369

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:sf

**Review by emanuelfisilva — COMMENTED** [review]
LGTM

**Comment by emanuelfisilva** [comment]
Thank you very much @austinchiang 
Forwarded: https://github.com/emanuelfisilva/liferay-portal/pull/101

**Pull request closed without merging**
