### PR TITLE
LRQA-68345 Refactor Data Engine paths and macros

### PR DESCRIPTION
**Pull request by thaisfrota**
[LRQA-68345](https://issues.liferay.com/browse/LRQA-68345)

### CODE REVIEW

**Comment by thaisfrota** [comment]
ci:test:sf

**Comment by thaisfrota** [comment]
ci:test:data-engine

**Review by emanuelfisilva — APPROVED** [review]
LGTM

**Comment by emanuelfisilva** [comment]
ci:forward

**Pull request closed without merging**
