### PR TITLE
master-qa-126896

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/LPS-126896
Submit to master.
@TonyMa888 @brianwulbern

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
@emanuelfisilva @chaowang-123 To speed up the review process I'll start reviewing the pulls from the China guys directly for DM stuff. Thanks! 

Sent here: https://github.com/liferay-lima/liferay-portal/pull/1441

**Comment by austinchiang** [comment]
ci:close

**Pull request closed without merging**
