### PR TITLE
LPS-135700 Create Objects Team Test Suite

### PR DESCRIPTION
**Pull request by emanuelfisilva**
[LPS-135700](https://issues.liferay.com/browse/LPS-135700) - Create Test Suite for Objects

- LPS-135700 Add Objects Test Suite on test.properties
- LPS-135700 Add Objects Tests info on ci.properties

### CODE REVIEW

**Comment by emanuelfisilva** [comment]
ci:test:sf

**Comment by emanuelfisilva** [comment]
ci:forward

**Comment by emanuelfisilva** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
ci:close

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Pull request closed without merging**
