### PR TITLE
LPS-127746 Create Data Engine component for TestRay and assign test to it

### PR DESCRIPTION
**Pull request by david-gutierrez-mesa**
https://issues.liferay.com/browse/LPS-127746

cc/ @alexcandidos @manoelcyreno

### CODE REVIEW

**Comment by david-gutierrez-mesa** [comment]
ci:test:sf

**Comment by david-gutierrez-mesa** [comment]
ci:test:relevant

**Comment by david-gutierrez-mesa** [comment]
Failing tests are not related.

**Comment by emanuelfisilva** [comment]
LGTM

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Directly send to https://github.com/brianchandotcom/liferay-portal/pull/98714

**Pull request closed without merging**
