### PR TITLE
LRQA-65791 LRQA-68162 LRQA-67534 LRQA-67535 LRQA-67479

### PR DESCRIPTION
**Pull request by guivilarim**
LRQA-68162 - Investigate CI failure of CPDynamicdatalists#AddListRecordWithHTMLField
LRQA-67534 - Investigate CI failure of DMFieldGroups#EditFieldOnDuplicatedFieldGroup
LRQA-67535 - Investigate CI failure of FieldGroups#EditFieldOnDuplicatedFieldGroup
LRQA-67479 - Investigate CI failure of Fieldsets#EditFieldsetPropertiesFromSideBar

### CODE REVIEW

**Comment by guivilarim** [comment]
ci:test:sf

**Comment by guivilarim** [comment]
ci:test:sf

**Review by emanuelfisilva — APPROVED** [review]
LGTM

**Comment by emanuelfisilva** [comment]
ci:forward

**Pull request closed without merging**
