### PR TITLE
Fix Data Engine Tests - LRQA-67482

### PR DESCRIPTION
**Pull request by thaisfrota**
[LRQA-67482](https://issues.liferay.com/browse/LRQA-67482)

### CODE REVIEW

**Comment by thaisfrota** [comment]
ci:test:sf

**Comment by thaisfrota** [comment]
ci:test:data-engine

**Comment by emanuelfisilva** [comment]
LGTM. 
Great work @thaisfrota

**Comment by emanuelfisilva** [comment]
ci:forward

**Pull request closed without merging**
