### PR TITLE
LRQA-67199 Refactor Data Engine macro

### PR DESCRIPTION
**Pull request by thaisfrota**
[LRQA-67199](https://issues.liferay.com/browse/LRQA-67199)

### CODE REVIEW

**Comment by thaisfrota** [comment]
ci:test:sf

**Comment by thaisfrota** [comment]
ci:test:data-engine

**Review by emanuelfisilva — APPROVED** [review]
LGTM
Great job, @thaisfrota !

**Comment by emanuelfisilva** [comment]
ci:forward

**Pull request closed without merging**
