### PR TITLE
Fix Data Engine Tests - LRQA-66643 LRQA-67316

### PR DESCRIPTION
**Pull request by thaisfrota**
[LRQA-66643](https://issues.liferay.com/browse/LRQA-66643)
[LRQA-67316](https://issues.liferay.com/browse/LRQA-67316)

### CODE REVIEW

**Comment by thaisfrota** [comment]
ci:test:sf

**Comment by thaisfrota** [comment]
ci:test:data-engine

**Review by emanuelfisilva — APPROVED** [review]
LGTM

**Comment by emanuelfisilva** [comment]
ci:stop

**Comment by emanuelfisilva** [comment]
ci:forward

**Pull request closed without merging**
