### PR TITLE
Fix Data Engine Tests - LRQA-66643 LRQA-66645 LRQA-67429 LRQA-66646 LRQA-66938 LRQA-67316 LRQA-66647

### PR DESCRIPTION
**Pull request by thaisfrota**
[LRQA-66643](https://issues.liferay.com/browse/LRQA-66643)
[LRQA-66645](https://issues.liferay.com/browse/LRQA-66645)
[LRQA-67429](https://issues.liferay.com/browse/LRQA-67429)
[LRQA-66646](https://issues.liferay.com/browse/LRQA-66646)
[LRQA-66938](https://issues.liferay.com/browse/LRQA-66938)
[LRQA-67316](https://issues.liferay.com/browse/LRQA-67316)
[LRQA-66647](https://issues.liferay.com/browse/LRQA-66647)

### CODE REVIEW

**Comment by thaisfrota** [comment]
ci:test:sf

**Comment by thaisfrota** [comment]
ci:test:data-engine

**Comment by emanuelfisilva** [comment]
Thanks @thaisfrota . Great work!
The failing tests are not related to this PR.

**Comment by emanuelfisilva** [comment]
ci:forward

**Pull request closed without merging**
