### PR TITLE
Fix of Data Engine Tests - LRQA-65791 LRQA-67467 LRQA-66644

### PR DESCRIPTION
**Pull request by guivilarim**
LRQA-67467 Investigate CI failure of LocalizedFieldsetsWebContent#CreateEditAndDeleteLocalizedFieldset

LRQA-66644 Investigate CI failure of LocalizedFieldsetsWebContent#TranslateWebContentFromStructureWithFieldsetWithFieldGroup

### CODE REVIEW

**Comment by guivilarim** [comment]
ci:test:sf

**Comment by guivilarim** [comment]
ci:test:data-engine

**Comment by emanuelfisilva** [comment]
LGTM
Thanks @guivilarim

**Comment by emanuelfisilva** [comment]
ci:forward

**Pull request closed without merging**
