### PR TITLE
Fix Data Engine Tests - LRQA-67540

### PR DESCRIPTION
**Pull request by thaisfrota**
[LRQA-67540](https://issues.liferay.com/browse/LRQA-67540)

### CODE REVIEW

**Comment by thaisfrota** [comment]
ci:test:sf

**Comment by thaisfrota** [comment]
ci:test:data-engine

**Comment by emanuelfisilva** [comment]
LGTM
Thanks @thaisfrota

**Comment by emanuelfisilva** [comment]
ci:forward

**Pull request closed without merging**
