### PR TITLE
LRQA-66585 Data Engine Functional Tests

### PR DESCRIPTION
**Pull request by thaisfrota**
[LRQA-66585](https://issues.liferay.com/browse/LRQA-66585)

### CODE REVIEW

**Comment by thaisfrota** [comment]
ci:test:sf

**Comment by thaisfrota** [comment]
ci:test:data-engine

**Comment by emanuelfisilva** [comment]
LGTM
Great work @thaisfrota 

Failing tests are not related to this PR

**Comment by emanuelfisilva** [comment]
ci:forward

**Pull request closed without merging**
