### PR TITLE
Fix of Data Engine Tests - LRQA-65791 LRQA-67481 LRQA-67479

### PR DESCRIPTION
**Pull request by guivilarim**
LRQA-67479 | Investigate CI failure of Fieldsets#EditFieldsetPropertiesFromSideBar
LRQA-67481 | Investigate failure of LocalizedFieldsetsWebContent#TranslationPersistsAfterEditingAnother and LocalizedFieldsetsWebContent#DefaultTitlePersistsUponFirstlyTranslatingForAnotherLocale

### CODE REVIEW

**Comment by guivilarim** [comment]
ci:test:sf

**Comment by guivilarim** [comment]
ci:test:data-engine

**Comment by guivilarim** [comment]
ci:test:sf

**Comment by emanuelfisilva** [comment]
LGTM
Great work @guivilarim .

**Comment by emanuelfisilva** [comment]
ci:forward

**Pull request closed without merging**
