### PR TITLE
Fix of Data Engine Tests - LRQA-65791 LRQA-67534 LRQA-67535

### PR DESCRIPTION
**Pull request by guivilarim**
LRQA-67534 Investigate CI failure of DMFieldGroups#EditFieldOnDuplicatedFieldGroup
LRQA-67535 Investigate CI failure of FieldGroups#EditFieldOnDuplicatedFieldGroup

### CODE REVIEW

**Comment by guivilarim** [comment]
ci:test:sf

**Comment by guivilarim** [comment]
ci:test:data-engine

**Comment by guivilarim** [comment]
ci:test:sf

**Comment by emanuelfisilva** [comment]
Great job!
Forwarded https://github.com/emanuelfisilva/liferay-portal/pull/182

**Pull request closed without merging**
